### ISSUE TITLE
ImGuiKey_Y does not work

### ISSUE THREAD

**Issue by hyouteki** [Talkative-Banana/Gl_Craft#4]
https://github.com/Talkative-Banana/Gl_Craft/blob/b931a70af2af23847d3db1f2bcff261ce79d58b3/src/main.cpp#L126-L135

**Comment by IAA03** [comment]
In this line ,line 131 i think  '                                        if(!Perspective || Perspective)'
The condition is always true

**Comment by IAA03** [comment]
Also if else is used with keys if you only want one key at a time with priority, otherwise use if for each key so that they always get executed if used, and that goes for each nested conditions and ifs

**Comment by Talkative-Banana** [comment]
Thanks fixed!
